/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as SalesRouteRouteImport } from './routes/sales/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SalesIndexRouteImport } from './routes/sales/index'
import { Route as SalesSecretRouteImport } from './routes/sales/secret'
import { Route as AuthAuthViewRouteImport } from './routes/auth/$authView'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesRouteRoute = SalesRouteRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesIndexRoute = SalesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SalesRouteRoute,
} as any)
const SalesSecretRoute = SalesSecretRouteImport.update({
  id: '/secret',
  path: '/secret',
  getParentRoute: () => SalesRouteRoute,
} as any)
const AuthAuthViewRoute = AuthAuthViewRouteImport.update({
  id: '/auth/$authView',
  path: '/auth/$authView',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sales': typeof SalesRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth/$authView': typeof AuthAuthViewRoute
  '/sales/secret': typeof SalesSecretRoute
  '/sales/': typeof SalesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth/$authView': typeof AuthAuthViewRoute
  '/sales/secret': typeof SalesSecretRoute
  '/sales': typeof SalesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sales': typeof SalesRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth/$authView': typeof AuthAuthViewRoute
  '/sales/secret': typeof SalesSecretRoute
  '/sales/': typeof SalesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sales'
    | '/about'
    | '/auth/$authView'
    | '/sales/secret'
    | '/sales/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/auth/$authView' | '/sales/secret' | '/sales'
  id:
    | '__root__'
    | '/'
    | '/sales'
    | '/about'
    | '/auth/$authView'
    | '/sales/secret'
    | '/sales/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SalesRouteRoute: typeof SalesRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthAuthViewRoute: typeof AuthAuthViewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales': {
      id: '/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof SalesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/': {
      id: '/sales/'
      path: '/'
      fullPath: '/sales/'
      preLoaderRoute: typeof SalesIndexRouteImport
      parentRoute: typeof SalesRouteRoute
    }
    '/sales/secret': {
      id: '/sales/secret'
      path: '/secret'
      fullPath: '/sales/secret'
      preLoaderRoute: typeof SalesSecretRouteImport
      parentRoute: typeof SalesRouteRoute
    }
    '/auth/$authView': {
      id: '/auth/$authView'
      path: '/auth/$authView'
      fullPath: '/auth/$authView'
      preLoaderRoute: typeof AuthAuthViewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SalesRouteRouteChildren {
  SalesSecretRoute: typeof SalesSecretRoute
  SalesIndexRoute: typeof SalesIndexRoute
}

const SalesRouteRouteChildren: SalesRouteRouteChildren = {
  SalesSecretRoute: SalesSecretRoute,
  SalesIndexRoute: SalesIndexRoute,
}

const SalesRouteRouteWithChildren = SalesRouteRoute._addFileChildren(
  SalesRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SalesRouteRoute: SalesRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthAuthViewRoute: AuthAuthViewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
